files:
  "Dockerfile*":
    processors:
      - docker-arg-alpine-tag
      - docker-arg-alpine-digest
      - docker-arg-go-tag
      - docker-arg-go-digest
  ".github/workflows/*.yml":
    processors:
      - gha-golang-matrix
      - gha-golang-release
      - gha-uses-vx
      - gha-uses-semver
      - gha-uses-commit
  "Makefile":
    processors:
      - makefile-gomajor
      - makefile-go-vulncheck
      - makefile-markdown-lint
      - makefile-osv-scanner
      - makefile-staticcheck
  "go.mod":
    processors:
      - go-mod-golang-release
  ".osv-scanner.toml":
    processors:
      - osv-golang-release

processors:
  docker-arg-alpine-tag:
    key: "{{ .SourceArgs.repo }}"
    scan: "regexp"
    scanArgs:
      regexp: '^ARG ALPINE_VER=(?P<Version>[\d+\.\d+\.\d+]+)@(?P<SHA>sha256:[0-9a-f]+)\s*$'
    source: "registry-tag"
    sourceArgs:
      repo: "docker.io/library/alpine"
    filter:
      expr: '^v?\d+\.\d+\.\d+$'
    sort:
      method: "semver"
  docker-arg-alpine-digest:
    key: "{{ .SourceArgs.image }}"
    scan: "regexp"
    scanArgs:
      regexp: '^ARG ALPINE_VER=(?P<Tag>[\d+\.\d+\.\d+]+)@(?P<Version>sha256:[0-9a-f]+)\s*$'
    source: "registry-digest"
    sourceArgs:
      image: "docker.io/library/alpine:{{.ScanMatch.Tag}}"
  docker-arg-go-tag:
    key: "{{ .SourceArgs.repo }}"
    scan: "regexp"
    scanArgs:
      regexp: '^ARG GO_VER=(?P<Version>[a-z0-9\-\.]+)-alpine@(?P<SHA>sha256:[0-9a-f]+)\s*$'
    source: "registry-tag"
    sourceArgs:
      repo: "docker.io/library/golang"
    filter:
      expr: '^v?\d+\.\d+\.\d+$'
    sort:
      method: "semver"
  docker-arg-go-digest:
    key: "{{ .SourceArgs.image }}"
    scan: "regexp"
    scanArgs:
      regexp: '^ARG GO_VER=(?P<Tag>[a-z0-9\-\.]+)@(?P<Version>sha256:[0-9a-f]+)\s*$'
    source: "registry-digest"
    sourceArgs:
      image: "docker.io/library/golang:{{.ScanMatch.Tag}}"
  gha-golang-matrix:
    key: "golang-matrix"
    scan: "regexp"
    scanArgs:
      regexp: '^\s*gover: (?P<Version>\[["0-9, \.]+\])\s*$'
    source: "registry-tag"
    sourceArgs:
      repo: "docker.io/library/golang"
    filter:
      expr: '^v?\d+\.\d+$'
    sort:
      method: "semver"
    template: '["{{ index .VerMap ( index .VerList 2 ) }}", "{{ index .VerMap ( index .VerList 1 ) }}", "{{ index .VerMap ( index .VerList 0 ) }}"]'
  gha-golang-release:
    key: "golang-latest"
    scan: "regexp"
    scanArgs:
      regexp: '^\s*RELEASE_GO_VER: "(?P<Version>v?[0-9\.]+)"\s*$'
    source: "registry-tag"
    sourceArgs:
      repo: "docker.io/library/golang"
    filter:
      expr: '^v?\d+\.\d+$'
    sort:
      method: "semver"
  gha-uses-vx:
    key: "{{ .ScanMatch.Repo }}"
    scan: "regexp"
    scanArgs:
      regexp: '^\s+-?\s+uses: (?P<Repo>[^@/]+/[^@/]+)[^@]*@(?P<Commit>[0-9a-f]+)\s+#\s+(?P<Version>v?\d+)\s*$'
    source: "git-tag"
    sourceArgs:
      url: "https://github.com/{{ .ScanMatch.Repo }}.git"
    filter:
      expr: '^v?\d+$'
    sort:
      method: "semver"
  gha-uses-semver:
    key: "{{ .ScanMatch.Repo }}"
    scan: "regexp"
    scanArgs:
      regexp: '^\s+-?\s+uses: (?P<Repo>[^@/]+/[^@/]+)[^@]*@(?P<Commit>[0-9a-f]+)\s+#\s+(?P<Version>v?\d+\.\d+\.\d+)\s*$'
    source: "git-tag"
    sourceArgs:
      url: "https://github.com/{{ .ScanMatch.Repo }}.git"
    filter:
      expr: '^v?\d+\.\d+\.\d+$'
    sort:
      method: "semver"
  gha-uses-commit:
    key: "{{ .ScanMatch.Repo }}:{{ .ScanMatch.Ref }}"
    scan: "regexp"
    scanArgs:
      regexp: '^\s+-?\s+uses: (?P<Repo>[^@/]+/[^@/]+)[^@]*@(?P<Version>[0-9a-f]+)\s+#\s+(?P<Ref>[\w\d\.]+)\s*$'
    source: "git-commit"
    sourceArgs:
      url: "https://github.com/{{ .ScanMatch.Repo }}.git"
      ref: "{{ .ScanMatch.Ref }}"
    filter:
      expr: "^{{ .ScanMatch.Ref }}$"
  go-mod-golang-release:
    key: "golang-oldest"
    scan: "regexp"
    scanArgs:
      regexp: '^go (?P<Version>[0-9\.]+)\s*$'
    source: "registry-tag"
    sourceArgs:
      repo: "docker.io/library/golang"
    filter:
      expr: '^\d+\.\d+$'
    sort:
      method: "semver"
    template: '{{ index .VerMap ( index .VerList 2 ) }}'
  makefile-gomajor:
    key: "{{ .SourceArgs.url }}"
    scan: "regexp"
    scanArgs:
      regexp: '^GOMAJOR_VER\?=(?P<Version>v?[0-9\.]+)\s*$'
    source: "git-tag"
    sourceArgs:
      url: "https://github.com/icholy/gomajor.git"
    filter:
      expr: '^v?\d+\.\d+\.\d+$'
    sort:
      method: "semver"
  makefile-go-vulncheck:
    key: "{{ .SourceArgs.url }}"
    scan: "regexp"
    scanArgs:
      regexp: '^GO_VULNCHECK_VER\?=(?P<Version>v?[0-9\.]+)\s*$'
    source: "git-tag"
    sourceArgs:
      url: "https://go.googlesource.com/vuln.git"
    filter:
      expr: '^v?\d+\.\d+\.\d+$'
    sort:
      method: "semver"
  makefile-markdown-lint:
    key: "{{ .SourceArgs.repo }}"
    scan: "regexp"
    scanArgs:
      regexp: '^MARKDOWN_LINT_VER\?=(?P<Version>v?[0-9\.]+)\s*$'
    source: "registry-tag"
    sourceArgs:
      repo: "docker.io/davidanson/markdownlint-cli2"
    filter:
      expr: '^v?\d+\.\d+\.\d+$'
    sort:
      method: "semver"
  makefile-osv-scanner:
    key: "{{ .SourceArgs.url }}"
    scan: "regexp"
    scanArgs:
      regexp: '^OSV_SCANNER_VER\?=(?P<Version>v?[0-9\.]+)\s*$'
    source: "git-tag"
    sourceArgs:
      url: "https://github.com/google/osv-scanner.git"
    filter:
      expr: '^v?\d+\.\d+\.\d+$'
    sort:
      method: "semver"
  makefile-staticcheck:
    key: "{{ .SourceArgs.url }}"
    scan: "regexp"
    scanArgs:
      regexp: '^STATICCHECK_VER\?=(?P<Version>v?[0-9\.]+)\s*$'
    source: "git-tag"
    sourceArgs:
      url: "https://github.com/dominikh/go-tools.git"
    filter:
      expr: '^v\d+\.\d+\.\d+$'
    sort:
      method: "semver"
  osv-golang-release:
    key: "{{ .SourceArgs.repo }}"
    scan: "regexp"
    scanArgs:
      regexp: '^GoVersionOverride = "(?P<Version>v?[0-9\.]+)"\s*$'
    source: "registry-tag"
    sourceArgs:
      repo: "docker.io/library/golang"
    filter:
      expr: '^v?\d+\.\d+\.\d+$'
    sort:
      method: "semver"

scans:
  regexp:
    type: "regexp"

sources:
  git-commit:
    type: "git"
    args:
      type: "commit"
  git-tag:
    type: "git"
    args:
      type: "tag"
  registry-digest:
    type: "registry"
  registry-tag:
    type: "registry"
    args:
      type: "tag"
